name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install project dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Clone Juice Shop
      run: git clone https://github.com/nbabii/juice-shop.git --depth 1

    - name: Start Juice Shop server
      working-directory: juice-shop
      run: |
        npm install
        npm start &
        npx wait-on http://localhost:3000

    - name: Run Playwright tests
      run: CI=1 npx playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
